version: '3.8'

services:
  # Frontend - TapPrint Admin
  tapprint-admin:
    build:
      context: ./TapPrint-admin
      dockerfile: Dockerfile
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://tapprint-backend:3001
    depends_on:
      - tapprint-backend
    networks:
      - tapprint-network
    restart: unless-stopped

  # Backend - TapPrint API
  tapprint-backend:
    build:
      context: ./TapPrint-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./db/tapprint.db
      - JWT_SECRET=${JWT_SECRET:-your-secret-key}
    volumes:
      - ./TapPrint-backend/db:/app/db
      - ./TapPrint-backend/uploads:/app/uploads
    networks:
      - tapprint-network
    restart: unless-stopped

  # Cockpit - Management Dashboard
  tapprint-cockpit:
    build:
      context: ./TapPrint-cockpit
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://tapprint-backend:3001
    depends_on:
      - tapprint-backend
    networks:
      - tapprint-network
    restart: unless-stopped

networks:
  tapprint-network:
    driver: bridge

volumes:
  tapprint-db:
    driver: local
  tapprint-uploads:
    driver: local